---
- name: Retrieve and print hostname and IP address
  hosts: all
  gather_facts: yes
  tasks:
    - name: Print hostname
      debug:
        msg: "Hostname: {{ ansible_hostname }}"

    - name: Print IP address
      debug:
        msg: "IP Address: {{ ansible_default_ipv4.address }}"
